services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"

  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./scripts/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=10GB'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./scripts/loki:/etc/loki
      - loki_data:/loki
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fluent-bit:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./scripts/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./scripts/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    logging:
      driver: fluentd
      options:
        tag: nginx
    depends_on:
      - fluent-bit

volumes:
  grafana_data:
  prometheus_data:
  loki_data:  